version: "3.8"
services:
  web:
    build:
      context: ./php/web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - public
      - private
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - public
      - private
networks:
  public:
  private: